# Sensible defaults
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g display-time 2000
set -g extended-keys on
set -g extended-keys-format csi-u

# Use the local system clipboard
set -g allow-passthrough on
set -g set-clipboard on

# Theme: borders
set -g pane-border-lines single
set -g pane-border-style "fg=brightblack"
set -g pane-active-border-style "fg=brightblack"
set -g display-panes-active-colour cyan

# Theme: status
set -g status-style "fg=white"
set -g status-left ""
set -g status-right "#h"
set -g window-status-format "#I "
set -g window-status-current-format "#{?#{==:#{session_windows},1},,● }"
set -g window-status-current-style "fg=magenta"
set -g window-status-bell-style "fg=red,nobold"

set -g mode-style "fg=black,bg=brightwhite"
set -g message-style "fg=brightwhite,bg=default"

set -g copy-mode-match-style "bg=yellow,fg=black"
set -g copy-mode-current-match-style "bg=yellow,fg=black"

set -g menu-border-lines none
set -g menu-selected-style "fg=brightwhite,bg=brightblack,bold"
set -g popup-style "fg=brightwhite,bg=black"

# Vim-style pane navigation
bind -n C-M-h select-pane -L
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U
bind -n C-M-l select-pane -R

# Split window horizontally
bind -n C-M-\- split-window -v

# Split window vertically
bind -n C-M-\\ split-window -h

# Window navigation
bind -n C-M-Left  previous-window
bind -n C-M-Right next-window
bind -n C-M-Up    last-window
bind -n C-M-Down  last-window

# Create new window
bind -n C-M-n new-window

# Close the current window
bind -n C-M-q kill-window

# Close the current pane
bind -n C-M-w kill-pane

# Reload configuration
bind -n C-M-r source-file ~/.config/tmux/tmux.conf

# Enter command mode
bind -n C-M-\; command-prompt

# Select session
bind -n C-M-s choose-tree -Zs

# Use Vim-style keybindings in copy mode
set -g mode-keys vi
bind -n C-M-v copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send-keys -X cancel
