#!/usr/bin/env bash

# Fetch the key ID that's assocatied with the given email address from a keyserver.
get_gpg_keyid_by_email() {
    gpg --with-colons --auto-key-locate keyserver --locate-keys "$1" 2> /dev/null | awk -F: '$1 == "fpr" {print $10;}' | head -n1
}

set_git_author() {
    local file="${HOME}/.gitconfig.local"
    echo -e "Enter your Git credentials...\n"
    read -p "Name: " name
    read -p "Email: " email
    git config --file ${file} user.name "${name}"
    git config --file ${file} user.email "${email}"
    local key=$(get_gpg_keyid_by_email ${email})
    if [[ -z "$key" ]]
    then
        echo -e "\nCould not find your PGP public key on a keyserver."
        echo -e "Please import your public key manually and then enter your key ID"
        echo -e "using the following command (replace <KEY-ID> with your key ID):"
        echo -e "\ngit config --file ${file} user.signingkey \"<KEY-ID>\""
    else
        git config --file ${file} user.signingkey "${key}"
    fi
}

set_git_author
