#!/usr/bin/env bash

set_git_author() {
    local file="${HOME}/.gitconfig.local"
    echo -e "Enter your Git credentials...\n"
    read -p "Name: " name
    read -p "Email: " email
    git config --file ${file} user.name "${name}"
    git config --file ${file} user.email "${email}"
    echo -e "\nPlease import your public key manually and then enter the path to your"
    echo -e "key file using the following command (replace <KEY-PATH> with the path):"
    echo -e "\ngit config --file ${file} user.signingkey \"<KEY-PATH>\""
}

set_git_author
