#!/usr/bin/env bash

fish_path=$(command -v fish)

if ! [[ -x "$fish_path" ]]; then
    echo "Fish not found" >&2
    exit 1
fi

if ! grep -qx "$fish_path" /etc/shells; then
    sudo sh -c "echo $fish_path >> /etc/shells"
fi

chsh -s "$fish_path"
